spring.application.name=Bitly_Clone
spring.datasource.url=jdbc:oracle:thin:@TT02:1521:XE
spring.datasource.username=bitly
spring.datasource.password=Nishant
server.port=6060
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true